name: 'Build'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["build"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      mapping: '["noreverseangle"]'
      clipboard: '["mac"]'
      kmonad_os: '["mac"]'
